name: 'Happi Labels'
description: 'Add Labels to Pull Requests'
inputs:
  github-token:
    description: 'GitHub token for API Access'
    required: true
    default: ${{ github.token}}
outputs:
  test: # id of output
    description: 'Test output'
runs:
  using: 'node20'
  main: 'dist/index.js'
