on:
  pull_request:
    branches: [dev]

jobs:
  label-prs:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npm install @actions/core @actions/github
      - name: Run Labeler
        uses: ./.github/actions/pr-labeler
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
