name: Release

on:
  push:
    branches:
      - main
    
jobs:
  happi-labels-release:
    if: ${{ ! contains(github.event.head_commit.message, '[skip ci]') }}
    name: Semantic Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      
      - name: Set-up pnpm
        id: setup-node
        uses: pnpm/action-setup@v4
        with:
          version: 9
      
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install
        run: pnpm i --frozen-lockfile

      - name: SetUp Git Credentials
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          actor: 'HappiBot 🤖'

      - name: Run Release
        run: pnpm run release

      - name: List dist directory
        run: ls -la dist
